version: '3.3'

services:
  authelia:
    image: authelia/authelia
    restart: always
    volumes:
      - ./authelia:/config
    ports:
      - 172.17.0.1:9091:9091
    environment:
      - TZ=Australia/Melbourne