version: '3.3'

services:
  authelia:
    image: authelia/authelia
    restart: always
    volumes:
      - ./authelia:/config
    networks:
      - net
    ports:
      - 172.17.0.1:9091:9091
    environment:
      - TZ=Australia/Melbourne

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data
    networks:
      - net
    expose:
      - 6379
    environment:
      - TZ=Australia/Melbourne