version: '3.3'
services:
  authelia:
    image: authelia/authelia
    volumes:
      - ./config:/config
    ports:
      - 172.17.0.1:9091:9091
    restart: unless-stopped
    environment:
      - TZ=America/Chicago