###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: ${ADMIN_PASSWORD}
default_redirection_url: ${BASE_URL}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  # rules:
  #   # Rules applied to everyone
  #   - domain: public.example.com
  #     policy: bypass
  #   - domain: traefik.example.com
  #     policy: one_factor
  #   - domain: secure.example.com
  #     policy: two_factor

session:
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: ${ADMIN_PASSWORD}

  cookies:
    - name: authelia_session
      domain: ${DOMAIN} # Should match whatever your root protected domain is
      expiration: 3600 # 1 hour
      inactivity: 300 # 5 minutes

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${ADMIN_PASSWORD}${ADMIN_PASSWORD}
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username:
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    sender: ${SMTP_FROM_EMAIL}
